services:
  db:
    image: postgres:15
    container_name: '4437aafad83ef1154d6a59ea'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: 'bbb769b617ac1201242cab57'
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: '51e6c48cab6ab5808dfabcb5'
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:create db:migrate && bin/rails server -b 0.0.0.0"
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: '455aac53c20aeadfd29e140b9fd2b544'
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8080:3000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data: